### ISSUE TITLE
1. Add <th> table header tag to table in admin/mod_accomodation/view.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#14]
Make changes on admin/mod_accomodation/view.php
![image](https://user-images.githubusercontent.com/102914802/212326664-d4e360e6-4835-4aca-ad21-afc6115aa460.png)

**Comment by Sarween** [comment]
Alright, I will check the error and fix it

**Comment by PUAJINGSHENG** [comment]
The bug is fixed, then issue is closed
