### ISSUE TITLE
4. Add "<th>" headers to this "<table>" at admin/mod_reports/search.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#17]
Add <th> table header tag into the table, so it can increase the readability of the code
![image](https://user-images.githubusercontent.com/102914802/212329673-5a63f086-0c0f-48fb-8e95-c3f722947092.png)

**Comment by Sarween** [comment]
I will make changes on it

**Comment by PUAJINGSHENG** [comment]
It is settle!
