### ISSUE TITLE
6. Review the data-flow - use of uninitialized value at booking/logininfo.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#21]
Variables should be initialized before use.
![image](https://user-images.githubusercontent.com/102914802/212333372-d839238e-7759-439a-9911-38bcb356aeb0.png)

**Comment by ZHIYAN2222** [comment]
Alright,later I will try to fix it

**Comment by PUAJINGSHENG** [comment]
It is solved!
