### ISSUE TITLE
7. Add "<th>" headers to this "<table>" at booking/payment.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#22]
Add <th> table header tag into the table to increase the readability of the source code.
![image](https://user-images.githubusercontent.com/102914802/212333871-be64ab4c-94b0-4a74-b965-48afb82814f6.png)

**Comment by YS0242** [comment]
OK, I will try to fix it

**Comment by PUAJINGSHENG** [comment]
The issue is fixed, then the issue will be closed
