### ISSUE TITLE
11. Refactor this loop to do more than one iteration at includes/database.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#28]
Loops with at most one iteration should be refactored.
![image](https://user-images.githubusercontent.com/102914802/212342464-11578f85-612f-4460-b191-19d831d4cf6d.png)

**Comment by Sarween** [comment]
It looks like difficult to fix, let me check how to fix first

**Comment by PUAJINGSHENG** [comment]
It is solved!
