### ISSUE TITLE
12. Review the data-flow - use of uninitialized value at includes/session.php

### ISSUE THREAD

**Issue by PUAJINGSHENG** [PUAJINGSHENG/HOTEL-RESERVATION-SYSTEM#29]
Variables should be initialized before use.
![image](https://user-images.githubusercontent.com/102914802/212343894-e6f7836e-b977-47a0-89ad-57864dcebc8c.png)

**Comment by ZHIYAN2222** [comment]
It seems like the last change request, maybe I can use experience before to make changes on it

**Comment by PUAJINGSHENG** [comment]
It is solved!
